# Generated by Django 5.1.2 on 2024-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
    ]
