# Generated by Django 5.1.2 on 2024-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalendario', '0002_feriados'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_oficial',
            field=models.BooleanField(default=False),
        ),
    ]
