# Generated by Django 5.1.2 on 2024-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalendario', '0003_evento_es_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='planificacion_interna',
            field=models.BooleanField(default=False),
        ),
    ]
