# Generated by Django 5.1.2 on 2024-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('inicio de semestre', 'Inicio de semestre'), ('fin de Semestre', 'Fin de Semestre'), ('inicio de Inscripción de Asignaturas', 'Inicio de Inscripción de Asignaturas'), ('fin de Inscripción de Asignaturas', 'Fin de Inscripción de Asignaturas'), ('receso Académico', 'Receso Académico'), ('feriado Nacional', 'Feriado Nacional'), ('feriado Regional', 'Feriado Regional'), ('inicio de Plazos de Solicitudes Administrativas', 'Inicio de Plazos de Solicitudes Administrativas'), ('fin de Plazos de Solicitudes Administrativas', 'Fin de Plazos de Solicitudes Administrativas'), ('inicio de Plazos para la Gestión de Beneficios', 'Inicio de Plazos para la Gestión de Beneficios'), ('fin de Plazos para la Gestión de Beneficios', 'Fin de Plazos para la Gestión de Beneficios'), ('ceremonia de Titulación o Graduación', 'Ceremonia de Titulación o Graduación'), ('reunión de Consejo Académico', 'Reunión de Consejo Académico'), ('talleres y Charlas', 'Talleres y Charlas'), ('día de Orientación para Nuevos Estudiantes', 'Día de Orientación para Nuevos Estudiantes'), ('eventos Extracurriculares', 'Eventos Extracurriculares'), ('inicio de Clases', 'Inicio de Clases'), ('ultimo Día de Clases', 'Último Día de Clases'), ('día de Puertas Abiertas', 'Día de Puertas Abiertas'), ('suspensión de Actividades Completa', 'Suspensión de Actividades Completa'), ('suspensión de Actividades Parcial', 'Suspensión de Actividades Parcial')], max_length=100),
        ),
    ]
